### ISSUE TITLE
Ensure kafka_install_parent_dir exists

### ISSUE THREAD

**Issue by rakshazi** [andrewrothstein/ansible-kafka#3]
Hello!
When `kafka_install_parent_dir` does not exists, Ansible fails with error.

Please, add following task before `unarchive...` task:

```yml
- name: "ensure {{ kafka_install_parent_dir }} exists"
      become: yes
      become_user: root
      file:
        path: "{{ kafka_install_parent_dir }}"
        state: directory
```
